"""empty message

Revision ID: 8673c7888590
Revises: 
Create Date: 2019-03-22 01:00:24.606973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8673c7888590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itcode', sa.String(length=12), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineer_itcode'), 'engineer', ['itcode'], unique=False)
    op.create_table('process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('engineer_id', sa.String(length=10), nullable=True),
    sa.Column('time', sa.Date(), nullable=True),
    sa.Column('process_one', sa.String(length=10), nullable=True),
    sa.Column('process_two', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ticket_type', sa.String(length=10), nullable=True),
    sa.Column('assinge_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('assigne_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_number'), 'ticket', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_number'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_table('process')
    op.drop_index(op.f('ix_engineer_itcode'), table_name='engineer')
    op.drop_table('engineer')
    # ### end Alembic commands ###
